version: '3.8'

services:
  backend:
    build:
      context: ./backend  
    dockerfile: Dockerfile.dev    
    ports:
      - "8090:8090"
    volumes:
      - /app/node_modules
      - ./backend:/app
    stdin_open: true
    networks:
      - applyhelper-network

  frontend:
    build:
      context: ./frontend
    dockerfile: Dockerfile.dev
    ports:
      - "3010:3010"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    networks:
      - applyhelper-network
    depends_on:
      - backend

networks:
  applyhelper-network:
    driver: bridge
