version: "3.8"

services:
  backend:
    image: psp0/applyhelper_backend:latest
    container_name: backend
    networks:
      - applyhelper-network
    environment:
      - CHUNGYAK_INFO_API_KEY=${CHUNGYAK_INFO_API_KEY}
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    ports:
      - "8080:8080"

  frontend:
    image: psp0/applyhelper_frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - applyhelper-network
    depends_on:
      - backend
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "4318:4318"
      - "16686:16686"
      - "14268:14268"
    networks:
      - applyhelper-network

networks:
  applyhelper-network:
    driver: bridge
